camera:
    #crop_area: [0., 0., 1., 0.677662037037037]  # 0.25, 0.25, 0.75, 0.75
    crop_area: [0., 0., 1., 0.7277]  # 0.25, 0.25, 0.75, 0.75
    wh: [1280, 960]

streamer:
    enable: true
    host: '127.0.0.1'
    port: 9527
    route: /meal
    size: [640, 480]
    quality: 40

AI:
    handwash:
        path: 'best_0.9690_0.9930_epoch_47_handwash-1472_fp16.dla'
        score_thresh: 0.5
        iou_thresh: 0.4
        input_wh: [448, 448]
        agnostic_nms: false
        classes:
            - step_1
            - step_2
            - step_3
            - step_4
            - step_5
            - step_6

log:
    folder: '/mnt/reserved/log'
    level: INFO

video:
    base_dir: /mnt/reserved/record/stream
    frame_w: 640
    frame_h: 480
    fps: 30
    periods: [
        [9, 10],
        [10, 11],
        [11, 12],
        [12, 13],
        [13, 14],
        [14, 15],
        [15, 16],
        [16, 17],
        [17, 18],
        [18, 19],
        [19, 20],
        [20, 21]
    ]
    bitrate: 3
    suffix: ''